import { Product } from '@/types';

export const PRODUCTS_DATA: Product[] = [
  {
    id: 'prod-1',
    title: 'NewsFast — Template Blogger Portal Berita Premium',
    slug: 'newsfast-template-blogger-portal-berita',
    shortDescription: 'Template Blogger responsif, ultra cepat, SEO-friendly, dan dioptimasi Google AdSense.',
    description: 'NewsFast adalah template Blogger profesional yang dirancang khusus untuk situs berita, majalah online, dan blog bertrafik tinggi. Dilengkapi dengan widget iklan bawaan, mode gelap otomatis, dan kecepatan situs 98+ Google PageSpeed.',
    category: 'Template Blogger',
    price: 149000,
    discountPrice: 199000,
    version: 'v2.4.0',
    demoUrl: 'https://newsfast-demo.blogspot.com',
    downloadUrl: 'https://duniadigitalia.com/downloads/newsfast-v2.4.0.zip',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Kecepatan 98+ PageSpeed', 'Optimasi Iklan AdSense Ready', 'SEO Schema Structured Data', 'Dark Mode Toggle Auto', 'Widget Berita Terpopuler & Breaking News'],
    salesCount: 342,
    rating: 4.9,
    reviewCount: 48,
    isFeatured: true,
    changelog: [
      { version: 'v2.4.0', date: '10 Jan 2026', notes: ['Pembaruan skema JSON-LD berita', 'Optimasi CLS & LCP'] }
    ],
    createdAt: '2026-01-05',
    updatedAt: '2026-01-10',
  },
  {
    id: 'prod-2',
    title: 'Tokodigital — Next.js 15 E-Commerce & Marketplace App',
    slug: 'tokodigital-nextjs-ecommerce-marketplace',
    shortDescription: 'Source code toko online full-stack Next.js 15, Tailwind v4, dan Tripay Payment Gateway.',
    description: 'Source code lengkap untuk toko online modern. Siap pakai dengan integrasi Tripay (QRIS, VA, Indomaret), manajemen produk Firestore, dan panel admin terpadu.',
    category: 'Website Toko Online',
    price: 349000,
    discountPrice: 499000,
    version: 'v1.2.0',
    demoUrl: 'https://tokodigital.duniadigitalia.com',
    downloadUrl: 'https://duniadigitalia.com/downloads/tokodigital-v1.2.0.zip',
    thumbnail: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Next.js 15 App Router & React 19', 'Pembayaran Otomatis Tripay QRIS/VA', 'Firestore Database & Auth', 'Generasi Invoice PDF', 'Admin Panel Produk & Transaksi'],
    salesCount: 189,
    rating: 5.0,
    reviewCount: 32,
    isFeatured: true,
    createdAt: '2026-01-15',
    updatedAt: '2026-01-15',
  },
  {
    id: 'prod-3',
    title: 'OmniDash — Template Admin Dashboard React & Tailwind',
    slug: 'omnidash-template-admin-dashboard',
    shortDescription: 'Template dashboard admin modern dengan 50+ komponen UI dan grafik interaktif.',
    description: 'OmniDash dirancang untuk mempercepat pembuatan aplikasi SaaS dan internal tool. Memiliki komponen UI lengkap, chart analitik, serta mode terang dan gelap.',
    category: 'Template Admin Dashboard',
    price: 199000,
    discountPrice: 279000,
    version: 'v3.0.1',
    demoUrl: 'https://omnidash-demo.duniadigitalia.com',
    downloadUrl: 'https://duniadigitalia.com/downloads/omnidash-v3.0.1.zip',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['50+ Komponen UI Siap Pakai', 'Recharts Analytics Charts', 'TypeScript Ready', 'Desain Clean & Minimalis'],
    salesCount: 215,
    rating: 4.8,
    reviewCount: 29,
    isFeatured: true,
    createdAt: '2025-12-20',
    updatedAt: '2026-01-08',
  },
  {
    id: 'prod-4',
    title: 'Master Prompt ChatGPT & Midjourney 500+',
    slug: 'master-prompt-chatgpt-midjourney',
    shortDescription: 'Kumpulan 500+ prompt AI pilihan untuk bisnis, copywriting, coding, dan desain visual.',
    description: 'Tingkatkan produktivitas kerja Anda hingga 10x lipat dengan koleksi prompt AI profesional teruji untuk pemasaran digital, konten media sosial, dan pembuatan gambar.',
    category: 'AI Prompt & Tools',
    price: 79000,
    discountPrice: 129000,
    version: 'v2026.1',
    demoUrl: '',
    downloadUrl: 'https://duniadigitalia.com/downloads/master-prompt-2026.pdf',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    screenshots: [],
    features: ['500+ Prompt Teruji', 'Kategori Bisnis & Copywriting', 'Prompt Visual Generator Art', 'Bonus Update Gratis 1 Tahun'],
    salesCount: 520,
    rating: 4.9,
    reviewCount: 84,
    isFeatured: false,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
];
